import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans({
	weight: ['300', '400', '500', '700'],
	style: ['normal'],
	subsets: ['latin', 'cyrillic'],
	display: 'swap',
	preload: true,
});

export const metadata: Metadata = {
	title: 'ShopCourse',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru" className={notoSans.className}>
			<head></head>
			<body>{children}</body>
		</html>
	);
}
